apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
  namespace: learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
        - name: frontend
          image: frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-service
  namespace: learning
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: frontend-nginx
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nextjs-nginx-ingress
#   namespace: learning
# spec:
#   rules:
#     - host: local-player.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend-nginx-service
#                 port:
#                   number: 80
