apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: learning
type: Opaque
data:
  mongo-username: YWRtaW4=
  mongo-password: MTIzNDU2Nzg5
  mongo-host: bW9uZ29kYi1zZXJ2aWNl
  mongo-port: MjcwMTc=
